#ifndef TOWERDEFENSE_GAME_MODULEDEFINITIONS_H
#define TOWERDEFENSE_GAME_MODULEDEFINITIONS_H

#define USING_NAMESPACE_TGAME_CORE using namespace TGEngine::core;

#endif// TOWERDEFENSE_GAME_MODULEDEFINITIONS_H
