name: Linux

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:

  build:

    name: Ubuntu 18.04
    runs-on: ubuntu-latest
    container: ubuntu:trusty

    steps:
      - name: Get repository name.
        run: echo ::set-env name=REPO_NAME::${GITHUB_REPOSITORY##*/}
      - name: Clone.
        uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: First set up.
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y --fix-missing \
          git zip cron curl cmake wget python llvm libxml2-dev build-essential libssl-dev inotify-tools \
          checkinstall libx11-dev libxext-dev zlib1g-dev libpng-dev libjpeg-dev libfreetype6-dev libxml2-dev \
          libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
          cd /opt && wget http://www.imagemagick.org/download/ImageMagick.tar.gz
          tar -zxf ImageMagick.tar.gz && ImageMagickPath=$(ls | grep 'ImageMagick-') && cd ${ImageMagickPath}
          touch configure && ./configure && make && make install && ldconfig /usr/local/lib && convert --version
          cd /var && git clone https://github.com/emscripten-core/emsdk.git emsdk && cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source /var/emsdk/emsdk_env.sh
          echo "source /var/emsdk/emsdk_env.sh\n" >> /etc/profile
          emcc --version